#!/usr/bin/python3
import pygame as pg
import fileinput

from math import *

pg.init()                                 # inicialização do sistema

# altura e largura da arena, em células
H, W = 20,20

# largura da célula
l = 20
# altura da célula
L = 2*l/sqrt(3)

# cria a janela
scr = pg.display.set_mode((2*W*l+l,int(1.5*L*H+L/2)))
# só para simplificar, atualização da imagem
atu = pg.display.update


# pinta o fundo da janela
scr.fill((0,200,0))
atu()

def convert(i ,j):
    """
    Converte a coordenada (i,j) para a posição em pixels na janela
    """
    x = (1 + i%2)*l + 2*j*l
    y = 1.5*i*L + L
    return x,y

class Robô(pg.sprite.Sprite):
    """
    Representa um Robô, possui uma imagem
    """
    def __init__(s, img):
        """
        Construtor, img é o nome do arquivo com a imagem
        """
        pg.sprite.Sprite.__init__(s)
        s.image = pg.image.load(img)
        s.rect = s.image.get_rect()

    def draw(s, i,j):
        """
        Desenha o robô na célula (i,j)
        """
        x, y = convert(i,j)

        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect

        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)

class Base(pg.sprite.Sprite):
    def __init__(s, img, i, j):
        pg.sprite.Sprite.__init__(s)
        s.image = pg.image.load(img)
        s.rect = s.image.get_rect()
        s.i = i
        s.j = j

    def draw(s):
        x, y = convert(s.i, s.j)
        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect

        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)

class Cristal(pg.sprite.Sprite):
    def __init__(s, quantidade, i, j):
        pg.sprite.Sprite.__init__(s)
        s.quantidade = quantidade
        s.image = pg.image.load("{}c.png".format(quantidade))
        s.rect = s.image.get_rect()
        s.i = i
        s.j = j

    def draw(s):
        x, y = convert(s.i, s.j)
        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect
        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)



class cell:
    """
    Representa uma das células da arena
    """
    def __init__(s,i,j):
        """
        Construtor, i e j formam a coordenada
        """
        # Posição do centro
        s.cx, s.cy = convert(i,j)
        # Cor (pode ser passada para o construtor no futuro)
        s.cor = (200,200,200)

        # Vértices do hexágono
        s.pontos = (
            (s.cx,   s.cy-L),
            (s.cx+l, s.cy-L/2),
            (s.cx+l, s.cy+L/2),
            (s.cx,   s.cy+L),
            (s.cx-l, s.cy+L/2),
            (s.cx-l, s.cy-L/2),
            )

    def draw(s) :
        """
        Desenha a célula
        """
        pg.draw.polygon(scr, s.cor, s.pontos, 0)
        pg.draw.lines(scr, (0,0,0), True, s.pontos, 2)


# Construção da matriz que representa a arena
arena = []
for i in range(H):
    arena.append([])
    for j in range(W):
        arena[i].append(cell(i,j))
        arena[i][j].draw()

# lista dos robôs definidos
robs = {}
bases = []
cristais = []

# atualiza a janela
atu()


def drawAll():
    # redesenha a célula original (apaga o robô)
    if 0 <= oi  < W and 0 <= oj < H:
        arena[oi][oj].draw()

    # desenha o robô na célula de destino
    if 0 <= di  < W and 0 <= dj < H and ri in robs:
        robs[ri].draw(di,dj)

    for base in bases:
        base.draw()

    for cristal in cristais:
        cristal.draw()

def recolheCristais(i, j):
    for cristal in cristais:
        if cristal.i == i and cristal.j == j:
            if cristal.quantidade > 1:
                cristal.quantidade -= 1
                cristal.image = pg.image.load("{}c.png".format(cristal.quantidade))
                print("Tentando recolher cristal")
            else:
                arena[cristal.i][cristal.j].draw()
                cristais.remove(cristal)



# Leitura dos comandos pela entrada padrão ou de um arquivo
for line in fileinput.input():
    r = line.split()

    # linha começando com 'fim', termina o programa
    if r[0] == 'fim':
        break

    # linha começando com 'rob', inclui um robô,
    # o segundo argumento na linha é a imagem
    if r[0] == 'rob':
        robs[int(r[2])] = Robô(r[1])
        continue

    # linha de movimentação:
    # robô, coordenadas originais, coordenadas finais
    if r[0] == 'base':
        bases.append(Base(r[1], int(r[2]), int(r[3])))
        continue

    if r[0] == 'cristal':
        cristais.append(Cristal(int(r[1]), int(r[2]), int(r[3])))
        continue

    if r[0] == 'remove':
        if r[1] == 'rob':            
            del robs[int(r[2])]
            arena[int(r[3])][int(r[4])].draw()
        continue

    if r[0] == 'recolhe':
        recolheCristais(int(r[1]), int(r[2]))
        continue

    ri, oi, oj, di, dj = list(map(int, r))

    drawAll()

    # tempo de espera para atualização, apenas para testes
    pg.time.wait(300)

    atu()

pg.quit()
# Local variables:
# mode: python
# End:
