#!/usr/bin/python3

# Hugo Mitsumori 8941262
# Paulo Araujo   8941112

"""
Lê, na entrada padrão, um programa na linguagem de montagem da máquina
virtual e retorna um programa em C que executa este programa.

Uso:
    montador < entrada > saida
"""
from sys import stdin
import re

l = stdin.readline()
ip = 0

tabsim = {}
print("#include <stdio.h>\n#include \"maq.h\"\n")
print("INSTR programa[] = {")
while l:
    label = op = ""
    arg   = "{NUM, 0}"
    try:
        l = l[:l.index('#')]
    except:
        pass
    keys = l.split()
    if len(keys) > 0 and keys[0].endswith(":"):
        label = keys[0][:-1]              #jogando fora o ':'
        tabsim[label]="{NUM, "+ str(ip) + "}"
        keys.pop(0)
    if len(keys) > 0:
        op = keys.pop(0)
    if len(keys) > 0:
        struct = re.search(r'\{.+\}', l, re.M|re.I)
        if struct:
            arg = struct.group()
        else:
            arg = keys.pop(0)
            if arg.isdigit():
                arg = "{NUM, " + arg +"}"
            if arg in tabsim:
                arg = tabsim[arg]
    if op != "":
        print("  {%s, %s},"%(op,arg))
    else:
        print()
    l = stdin.readline()
    ip += 1
print("};\n")

print( "int main(int ac, char **av) {")
print( "\tMaquina *maq = cria_maquina(programa);")
print( "\texec_maquina(maq, 1000);")
print( "\tdestroi_maquina(maq);")
print( "\treturn 0;")
print( "}")
    




# Local variables:
# mode: python
# End:
# mode: python
# End:
